services:
  web:
    build: ./vote/
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  worker:
    build: ./worker/
    depends_on:
      - redis
      - postgres
    networks:
      - my_network

  result:
    build: ./result/
    ports:
      - "8888:8888"
    volumes:
      - ./result:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  redis_data:
  postgres_data:

networks:
  my_network:
    driver: bridge
