services:
  web:
    image: voting_web:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    networks:
      - my_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: voting_worker:latest
    depends_on:
      - redis
      - postgres
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "dotnet", "--version"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  result:
    image: voting_result:latest
    ports:
      - "8888:8888"
    volumes:
      - ./result:/app
      - /app/node_modules
    depends_on:
      - worker
      - postgres
    networks:
      - my_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.106,rw"
      device: ":/export/redis_data"
  postgres_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.106,rw"
      device: ":/export/postgres_data"

networks:
  my_network:
    driver: overlay
