services:
  web:
    build: ./vote/
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

volumes:
  redis_data:

networks:
  my_network:
    driver: bridge
